theme: jekyll-theme-minimal
title: beak2003.github.io
description: This is Reggie's github page! I am a computer science major at Boise State University with an emphasis in machine learning. This is my first github page.
